name: Convert SVG to PNG

on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cairosvg

      - name: Run conversion script
        uses: johansolbakken/png-copy-action@main
        with:
          svg-folder: '.'
          png-folder: 'png-copy'
          github-token: ${{ secrets.GITHUB_TOKEN }}
