name: Convert SVG to PNG

on:
  push:
    paths:
      - '**/*.svg'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run conversion script
        uses: johansolbakken/png-copy-action@main  # Reference the external action repository
        with:
          svg-folder: '.'
          png-folder: 'png-copy'
          github-token: ${{ secrets.GITHUB_TOKEN }}
